<?php
/**
 * ReceiptSignature
 *
 * PHP version 5
 *
 * @category Class
 * @package  WooletClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 * Woleet API
 *
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/reference)** before reading this documentation.
 *
 * OpenAPI spec version: 1.10.0
 * Contact: contact@woleet.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace WooletClient\Model;

use \ArrayAccess;
use \WooletClient\ObjectSerializer;

/**
 * ReceiptSignature Class Doc Comment
 *
 * @category Class
 * @description Proof of signature (for proof of signature receipts only).
 * @package  WooletClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ReceiptSignature implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $swaggerModelName = 'receipt_signature';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $swaggerTypes = [
        'signed_hash' => 'string',
        'signed_identity' => 'string',
        'signed_issuer_domain' => 'string',
        'pub_key' => 'string',
        'signature' => 'string',
        'identity_url' => 'string'];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $swaggerFormats = [
        'signed_hash' => null,
        'signed_identity' => null,
        'signed_issuer_domain' => null,
        'pub_key' => null,
        'signature' => null,
        'identity_url' => null];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'signed_hash' => 'signedHash',
        'signed_identity' => 'signedIdentity',
        'signed_issuer_domain' => 'signedIssuerDomain',
        'pub_key' => 'pubKey',
        'signature' => 'signature',
        'identity_url' => 'identityURL'];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'signed_hash' => 'setSignedHash',
        'signed_identity' => 'setSignedIdentity',
        'signed_issuer_domain' => 'setSignedIssuerDomain',
        'pub_key' => 'setPubKey',
        'signature' => 'setSignature',
        'identity_url' => 'setIdentityUrl'];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'signed_hash' => 'getSignedHash',
        'signed_identity' => 'getSignedIdentity',
        'signed_issuer_domain' => 'getSignedIssuerDomain',
        'pub_key' => 'getPubKey',
        'signature' => 'getSignature',
        'identity_url' => 'getIdentityUrl'];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['signed_hash'] = isset($data['signed_hash']) ? $data['signed_hash'] : null;
        $this->container['signed_identity'] = isset($data['signed_identity']) ? $data['signed_identity'] : null;
        $this->container['signed_issuer_domain'] = isset($data['signed_issuer_domain']) ? $data['signed_issuer_domain'] : null;
        $this->container['pub_key'] = isset($data['pub_key']) ? $data['pub_key'] : null;
        $this->container['signature'] = isset($data['signature']) ? $data['signature'] : null;
        $this->container['identity_url'] = isset($data['identity_url']) ? $data['identity_url'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets signed_hash
     *
     * @return string
     */
    public function getSignedHash()
    {
        return $this->container['signed_hash'];
    }

    /**
     * Sets signed_hash
     *
     * @param string $signed_hash SHA256 hash (ie. the fingerprint) of the signed file.
     *
     * @return $this
     */
    public function setSignedHash($signed_hash)
    {
        $this->container['signed_hash'] = $signed_hash;
        return $this;
    }

    /**
     * Gets signed_identity
     *
     * @return string
     */
    public function getSignedIdentity()
    {
        return $this->container['signed_identity'];
    }

    /**
     * Sets signed_identity
     *
     * @param string $signed_identity X500 Distinguished Name representing the signed identity.
     *
     * @return $this
     */
    public function setSignedIdentity($signed_identity)
    {
        $this->container['signed_identity'] = $signed_identity;
        return $this;
    }

    /**
     * Gets signed_issuer_domain
     *
     * @return string
     */
    public function getSignedIssuerDomain()
    {
        return $this->container['signed_issuer_domain'];
    }

    /**
     * Sets signed_issuer_domain
     *
     * @param string $signed_issuer_domain Domain name of the identity issuer (ie. of the organization who verified the identity).
     *
     * @return $this
     */
    public function setSignedIssuerDomain($signed_issuer_domain)
    {
        $this->container['signed_issuer_domain'] = $signed_issuer_domain;
        return $this;
    }

    /**
     * Gets pub_key
     *
     * @return string
     */
    public function getPubKey()
    {
        return $this->container['pub_key'];
    }

    /**
     * Sets pub_key
     *
     * @param string $pub_key Public key of the signer.<br> **Currently only Bitcoin addresses are supported.**
     *
     * @return $this
     */
    public function setPubKey($pub_key)
    {
        $this->container['pub_key'] = $pub_key;
        return $this;
    }

    /**
     * Gets signature
     *
     * @return string
     */
    public function getSignature()
    {
        return $this->container['signature'];
    }

    /**
     * Sets signature
     *
     * @param string $signature Signature of the `signedHash` property using the public key `pubKey`, or, if any of `signedIdentity` or `signedIssuerDomain` is provided, signature of SHA256(`signedHash` + `signedIdentity` + `signedIssuerDomain`) using the public key `pubKey`.
     *
     * @return $this
     */
    public function setSignature($signature)
    {
        $this->container['signature'] = $signature;
        return $this;
    }

    /**
     * Gets identity_url
     *
     * @return string
     */
    public function getIdentityUrl()
    {
        return $this->container['identity_url'];
    }

    /**
     * Sets identity_url
     *
     * @param string $identity_url Web hook to use to verify the signer's identity.
     *
     * @return $this
     */
    public function setIdentityUrl($identity_url)
    {
        $this->container['identity_url'] = $identity_url;
        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed $value Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
