<?php
/**
 * SignatureRequestState
 *
 * PHP version 5
 *
 * @category Class
 * @package  WooletClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 * Woleet API
 *
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/reference)** before reading this documentation.
 *
 * OpenAPI spec version: 1.10.0
 * Contact: contact@woleet.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace WooletClient\Model;

use \WooletClient\ObjectSerializer;

/**
 * SignatureRequestState Class Doc Comment
 *
 * @category Class
 * @description State of the signature request.&lt;br&gt; If not set, the signature request is **stateless** and can be updated at any time (eg. to add new signers on the fly).&lt;br&gt; If set to &#x27;DRAFT&#x27; at creation time, the signature request is **stateful** and its state can be transitioned using the dedicated endpoint.&lt;br&gt; Available states:&lt;br&gt; - &#x60;DRAFT&#x60;: the signature request is being edited (only &#x60;DRAFT&#x60; signature requests can be updated)&lt;br&gt; - &#x60;PENDING&#x60;: the signature request is awaiting for its activation date&lt;br&gt; - &#x60;IN_PROGRESS&#x60;: the activation date has been reached, the signature request emails have been sent to the signers (if applicable) and the signatures are being collected&lt;br&gt; - &#x60;COMPLETED&#x60;: all signatures have been collected&lt;br&gt; - &#x60;CLOSED&#x60;: the signature request has been closed by the owner before all signatures could be collected&lt;br&gt; - &#x60;CANCELED&#x60;: the signature request has been canceled by the owner before all signatures could be collected&lt;br&gt; - &#x60;EXPIRED&#x60;: the deadline of the signature request has been reached before all signatures could be collected
 * @package  WooletClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SignatureRequestState
{
    /**
     * Possible values of this enum
     */
    const DRAFT = 'DRAFT';
    const PENDING = 'PENDING';
    const IN_PROGRESS = 'IN_PROGRESS';
    const COMPLETED = 'COMPLETED';
    const CLOSED = 'CLOSED';
    const CANCELED = 'CANCELED';
    const EXPIRED = 'EXPIRED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DRAFT,
            self::PENDING,
            self::IN_PROGRESS,
            self::COMPLETED,
            self::CLOSED,
            self::CANCELED,
            self::EXPIRED,];
    }
}
